[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

[control]
# Map H, J, K, L to arrows when control is held
h = left
j = down
k = up
l = right
